### ISSUE TITLE
Error when server unavailable

### ISSUE THREAD

**Issue by Levsha-cc** [swiggles/laravel-memcache#1]
If server is unavailable goes error like:
Whoops, looks like something went wrong.
MemcachePool::getversion(): Server 127.0.0.1 (tcp 11211, udp 0) failed with: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

It's bad, because even if something happened with memcache server, website still should work.

So, I'm offer to change code in vendor/swiggles/memcache/src/MemcacheConnector.php from this:
        if ($memcache->getVersion() === false)
        {
            throw new RuntimeException("Could not establish Memcache connection.");
        }
to this:
        try {
            if ($memcache->getVersion() === false)
            {
                \Log::critical("Could not establish Memcache connection.");
            }
        }
        catch(\Exception $e) {
            \Log::critical("Could not establish Memcache connection.");
        }

Or maybe I'm just bad in Laravel.
Thanks!

**Comment by swiggles** [comment]
Well spotted, good suggestion, I will review the code when I get back to work.

Feel free to make a pull request if you like in the meantime and give it a good test. I initially made this package just for local development purposes only on Windows OS running xampp as our live servers are all Linux and the standard memcache driver in laravel works fine for that.

**Comment by swiggles** [comment]
I think you would probably still throw the exception but just catch it and log it instead

**Comment by swiggles** [comment]
I haven't worked with Laravel for a while now, have realised after the pull request that this won't work. \Log can't be found as far as this package is concerned as it doesn't know where to find it.

Maybe this might help I just haven't got time to look into it properly at the moment sorry 
https://laravel.com/docs/5.1/events#framework-events
