### ISSUE TITLE
Composer not pull last fix

### ISSUE THREAD

**Issue by PaddyHu** [swiggles/laravel-memcache#6]
I try to use your package with Laravel 5.2, but I get an error:

"lass Swiggles\Memcache\MemcacheStore contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods "

I checked in your repository, this error was fixed but composer doesn't pull the the changes.

**Comment by swiggles** [comment]
Hi, could you try and delete the package from the vendor folder and run composer update again, I have made a new release for use with laravel 5.2 which means you will need to update your composer file to use "~2.0"
